# Server
server:
  port: 8888

spring:
  profiles: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #jpa 설정
  jpa:
    #mysql mode로 변경( dialect는 database방언을 통합해줌)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    show-sql: true

    # 가독성
    properties:
      hibernate.format_sql : true


    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: create
    open-in-view: false



  # js 절대경로 설정
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static

    database: mysql


  freemarker:
    cache: false

  ############## DB연결 ( mysql )
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://119.192.148.204:3306/system_failure_mgnt?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&useUnicode=true
    username: devcomm
    password: devcomm1234
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000
    test-on-borrow: true
    validation-query: select 1


# logging
logging:
  config: classpath:logback-local.xml